# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.boot_timeout=3000
  config.ssh.pty=false
  config.ssh.insert_key=false

  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
	vb.customize ["modifyvm", :id, "--memory", "2048"]
	vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "manager" do |node1|
	node1.vm.box_check_update = false
  	node1.vm.hostname="manager"
        node1.vm.network "public_network", auto_config: false,bridge:"en0: Wi-Fi (AirPort)"
        
        node1.vm.provision "shell",path: "bootstrap.sh"
  end

   config.vm.define "data1" do |data1|
	data1.vm.box_check_update = false
  	data1.vm.hostname="data1"
 	data1.vm.network "public_network", auto_config: false,bridge:"en0: Wi-Fi (AirPort)"

	data1.vm.provision "shell",
    		run: "always",
 		inline: "yum install -y net-tools && ifconfig eth1 192.168.101.204 netmask 255.255.0.0 up" 
	data1.vm.provision "shell",path: "bootstrap.sh"
  end

  config.vm.define "data2" do |data2|
        data2.vm.box_check_update = false
  	data2.vm.hostname="data2"
 	data2.vm.network "public_network", auto_config: false,bridge:"en0: Wi-Fi (AirPort)"

        data2.vm.provision "shell",
    		run: "always",
 		inline: "yum install -y net-tools && ifconfig eth1 192.168.101.205 netmask 255.255.0.0 up"
        data2.vm.provision "shell",path: "bootstrap.sh"
  end
  
#  config.vm.define "data3" do |data3|
#        data3.vm.box_check_update = false
#  	data3.vm.hostname="node4"
# 	data3.vm.network "public_network", auto_config: false,bridge:"en0: Wi-Fi (AirPort)"
#
#        data3.vm.provision "shell",
#    		run: "always",
# 		inline: "ifconfig eth1 192.168.101.206 netmask 255.255.0.0 up"
#        data3.vm.provision "shell",path: "bootstrap.sh"
#  end

  config.vm.define "sql" do |sql|
	sql.vm.box_check_update = false
  	sql.vm.hostname="sql"
 	sql.vm.network "public_network", auto_config: false,bridge:"en0: Wi-Fi (AirPort)"

        sql.vm.provision "shell",
                run: "always",
                inline: "yum install -y net-tools && ifconfig eth1 192.168.101.203 netmask 255.255.0.0 up"
	sql.vm.provision "shell",path: "bootstrap.sh"
  end

end
